import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const notoSerif = localFont({
  variable: "--font-noto-serif",
  src: [
    {
      path: "./fonts/NotoSerif-VariableFont_wdth,wght.ttf",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "./fonts/NotoSerif-Italic-VariableFont_wdth,wght.ttf",
      weight: "100 900",
      style: "italic",
    },
  ],
});

const germaniaOne = localFont({
  variable: "--font-germania-one",
  src: [{ path: "./fonts/GermaniaOne-Regular.ttf", weight: "400" }],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSerif.variable} ${germaniaOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
